services:
  database:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: fast-feet-db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
